name: Rust

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Precomp
      run: |
        chmod +x install-linux-deps.sh
        ./install-linux-deps.sh
        npm install -g @tauri-apps/cli@^1.6.0

    - name: Build autoupdater
      run: cargo build --release --manifest-path autoupdater/Cargo.toml --target x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release -p TeraLauncher
    - name: Build bridge
      run: cargo build --release --manifest-path launcher-bridge/Cargo.toml --target x86_64-pc-windows-gnu
    - name: Compress
      uses: vimtor/action-zip@v1
      with:
        files: autoupdater teralaunch launcher-bridge target/release/
        recursive: false
        dest: tera-launcher.zip

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: teralauncher
        path: tera-launcher.zip
